### ISSUE TITLE
No such file or directory: './tests/data/test_connection.json'

### ISSUE THREAD

**Issue by sajith** [atlanticwave-sdx/datamodel#24]
Running `python -m unittest` resulted in two errors:

```
======================================================================
ERROR: testImportConnection (tests.test_connection_handler.TestConnectionHandler)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sajith/projects/renci/aw-sdx/datamodel/tests/test_connection_handler.py", line 21, in testImportConnection
    self.handler.import_connection(CONNECTION_P2P)
  File "/home/sajith/projects/renci/aw-sdx/datamodel/sdxdatamodel/parsing/connectionhandler.py", line 37, in import_connection
    with open(file, 'r', encoding='utf-8') as data_file:
FileNotFoundError: [Errno 2] No such file or directory: './tests/data/test_connection.json'

======================================================================
ERROR: testConnection (tests.test_connection_validator.TestConnectionValidator)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sajith/projects/renci/aw-sdx/datamodel/tests/test_connection_validator.py", line 18, in setUp
    self.handler.import_connection(CONNECTION_P2P)
  File "/home/sajith/projects/renci/aw-sdx/datamodel/sdxdatamodel/parsing/connectionhandler.py", line 37, in import_connection
    with open(file, 'r', encoding='utf-8') as data_file:
FileNotFoundError: [Errno 2] No such file or directory: './tests/data/test_connection.json'

----------------------------------------------------------------------
Ran 17 tests in 0.950s

FAILED (errors=2)
```

Is this expected?

**Comment by YufengXin** [comment]
No-:)

I deleted an old test input file and forgot to change here. Just pushed in the fix.

Thanks

-Yufeng


On Jun 8, 2022, at 4:42 PM, Sajith Sasidharan ***@***.******@***.***>> wrote:


test_connection_validator
