### ISSUE TITLE
Missing modules when running tests

### ISSUE THREAD

**Issue by sajith** [atlanticwave-sdx/datamodel#27]
I did this:

```
$ python -m venv venv
$ source venv/bin/activate
$ python3 -m pip install -r requirements.txt 
$ python3 -m unittest
```

That resulted in some errors:

```
======================================================================
ERROR: tests.test_topology_graph (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests.test_topology_graph
Traceback (most recent call last):
  File "/usr/lib/python3.9/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.9/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/home/sajith/projects/renci/aw-sdx/datamodel/tests/test_topology_graph.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'


======================================================================
ERROR: tests.test_topology_manager (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests.test_topology_manager
Traceback (most recent call last):
  File "/usr/lib/python3.9/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.9/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/home/sajith/projects/renci/aw-sdx/datamodel/tests/test_topology_manager.py", line 4, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'


----------------------------------------------------------------------
Ran 15 tests in 0.057s

FAILED (errors=2)
```

**Comment by sajith** [comment]
PR #32 resolved this.
