### ISSUE TITLE
Refactor `import_connection_data()`

### ISSUE THREAD

**Issue by sajith** [atlanticwave-sdx/datamodel#46]
Consider the current implementation of `parsing.ConnectionHandler.import_connection_data()`:

https://github.com/atlanticwave-sdx/datamodel/blob/3a83c58fb81ca8af496d9946297544727399ea45/sdxdatamodel/parsing/connectionhandler.py#L15-L34

It looks that `id`, `name`, `ingress_port`, and `egress_port` can't be `None`, but others can be.  That is the assumption in `Connection`'s constructor too:

https://github.com/atlanticwave-sdx/datamodel/blob/3a83c58fb81ca8af496d9946297544727399ea45/sdxdatamodel/models/connection.py#L57-L80

But `import_connection_data()` will fail if any of the non-optional fields are `None`.  Quick test from Python shell:

```python
>>> from sdxdatamodel.parsing.connectionhandler import ConnectionHandler
>>> ch = ConnectionHandler()
>>> ch.import_connection_data({'id': 'xx', 'name': 'yy', 'ingress_port': [], 'egress_port': []})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "[...]/datamodel/sdxdatamodel/parsing/connectionhandler.py", line 32, in import_connection_data
    connection=Connection(id=id, name=name, start_time = start, end_time = end, bandwidth=bw, latency=la, ingress_port = ingress, egress_port = egress)
UnboundLocalError: local variable 'start' referenced before assignment
>>> 
```

**Comment by sajith** [comment]
Addressed in #47.
